### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by nguyenhuyanhh** [nguyenhuyanhh/cz4032#11]

**Comment by prabhjotvickygrewal** [comment]
[CZ4032_Presentation.pptx](https://github.com/nguyenhuyanhh/cz4032/files/1463501/CZ4032_Presentation.pptx)

Need to discuss what to put in few slides. This may go over 7 minutes so should do a trial run IMO

**Comment by nguyenhuyanhh** [comment]
Will do that on Monday!
