### ISSUE TITLE
More models?

### ISSUE THREAD

**Issue by nguyenhuyanhh** [nguyenhuyanhh/cz4032#18]

**Comment by tanvigupta97** [comment]
Do we have the time??

**Comment by nguyenhuyanhh** [comment]
optional I think, I can explore that since I don't have much for the weekend while you guys have DBSP/SecMgmt

**Comment by tanvigupta97** [comment]
Okay sure!
BTW I might probably have ARIMA code lying around haha, if you wanna reuse, lmk
