### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by nguyenhuyanhh** [nguyenhuyanhh/cz4032#8]
Yay!

**Comment by aashikaa** [comment]
[4032 report1.docx](https://github.com/nguyenhuyanhh/cz4032/files/1411219/4032.report1.docx)

Initial draft

**Comment by nguyenhuyanhh** [comment]
To-dos:
- [x] Pros and cons
- [x] Citations
- [x] Visualizations (#10)

**Comment by nguyenhuyanhh** [comment]
@aashikaa for you to keep track!

**Comment by aashikaa** [comment]
[4032 report1.docx](https://github.com/nguyenhuyanhh/cz4032/files/1463603/4032.report1.docx)

(everything other than score and visualisations)

**Comment by nguyenhuyanhh** [comment]
Report structure:
- [x] Abstract
- [x] Problem Description: Motivation, Problem Definition, Related Work
- [x] Approach: Methodology (Random Forest, XGBoost)
- [x] Implementation: Preprocessing, Feature Engineering
- [x] Results and Analysis: Results, Pros and Cons
- [x] Conclusion
- [x] References
